# Generated by Django 4.1.4 on 2023-02-22 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudx', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RandomWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=34)),
            ],
        ),
        migrations.AlterField(
            model_name='studentsdata',
            name='Darkskinned',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentsdata',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentsdata',
            name='firstname',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='studentsdata',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='studentsdata',
            name='lastname',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
    ]
