# Generated by Django 4.1.4 on 2023-02-28 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudx', '0003_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=70, null=True)),
                ('img', models.ImageField(blank=True, null=True, upload_to='api_img_upl')),
            ],
        ),
        migrations.DeleteModel(
            name='image',
        ),
    ]
