# Generated by Django 4.1.4 on 2023-02-28 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudx', '0004_images_delete_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='img',
            field=models.ImageField(default='busy-road.jpg', upload_to='api_img_upl'),
        ),
    ]
