# Generated by Django 4.1.4 on 2023-02-28 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudx', '0005_alter_images_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='api_img_upl'),
        ),
    ]
