# Generated by Django 4.1.4 on 2023-02-28 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudx', '0006_alter_images_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='img',
            field=models.ImageField(default='display.png', upload_to='api_img_upl'),
        ),
    ]
