# Generated by Django 4.1.4 on 2023-03-10 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudx', '0008_alter_images_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='testing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=70, null=True)),
                ('nickname', models.CharField(blank=True, max_length=70, null=True)),
            ],
        ),
    ]
