# Generated by Django 4.1.4 on 2023-03-11 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudx', '0009_testing'),
    ]

    operations = [
        migrations.AddField(
            model_name='testing',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
